ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  class:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 技术分享
      Role: 'acs:ram::1618696952265463:role/aliyunfcdefaultrole'
      LogConfig:
        Project: aliyun-fc-cn-hangzhou-2fa59841-f19f-54e9-bab4-33798e1c4eb2
        Logstore: function-log
      InternetAccess: true
    main:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs12
        Timeout: 60
        MemorySize: 512
        InstanceConcurrency: 1
        EnvironmentVariables: {}
      Events:
        defaultTrigger:
          Type: HTTP
          Properties:
            AuthType: anonymous
            Methods:
              - GET
              - POST
